config/routes.rb
Rails.application.routes.draw do
  root "songs#index"
  resources :artists
  # get "/songs" => "songs#index", as: :songs
  # get "/song/new" => "songs#new", as: :new_song
  # get "/song/:id" => "songs#edit", as: :edit_song
  #
  # post "/songs" => "songs#create"
  #
  # delete "/song/:id" => "songs#destroy", as: :destroy_song

  resources :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  validates :name, presence: true
  validates :duration, presence: true
  validates :duration, numericality: true

  belongs_to :artist

  def in_minutes
    "#{duration/ 60} minutes and #{duration % 60} seconds"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def new
    @song = Song.new
    artist_options
  end

  def create
    @song = Song.new(song_params)

    if @song.save
      redirect_to songs_path
    else
      render :new
    end
  end

  def edit
    @song = Song.find(params["id"])
    artist_options
  end

  def update
    @song = Song.find(params["id"])

    if @song.update(song_params)
      redirect_to songs_path
    else
      render :edit
    end
  end

  def destroy
    song = Song.find(params["id"])
    song.destroy

    redirect_to songs_path, notice: "Deleted song #{song.name}"
  end


  private
  def song_params
    params.require(:song).permit(:name, :duration, :artist_id)
  end

  def artist_options
    @artists = Artist.all.map { |a| [ a.name, a.id ] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jukebox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if song.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

    <ul>
    <% song.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/songs/_form.html.erb
<%= render "shared/error_messages", song: @song %>

<%= form_for song do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <br>
  <%= form.label :duration %>
  <%= form.number_field :duration %>
  <br>
  <%= form.select :artist_id, artists %>
  <br>
  <%= form.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing a Song</h1>

<%= render "form", song: @song, artists: @artists %>

app/views/songs/index.html.erb
<h1>Songs</h1>

<table>
  <tr>
    <th> Name </th>
    <th> Duration </th>
    <th> Artist </th>
    <th> Edit </th>
    <th> Delete </th>
  </tr>
    <% @songs.each do |song| %>
    <tr>
      <td> <%= song.name %> </td>
      <td> <%= song.duration %> </td>
      <td> <%= song.artist.name %></td>
      <td> <%= link_to "X", edit_song_path(id: song.id) %></td>
      <td> <%= link_to "X", song_path(id: song.id), method: :delete %></td>
    </tr>
    <% end %>
</table>

<br>
<%= link_to "New Song", new_song_path %>

app/views/songs/new.html.erb
<h1>Add a new Song</h1>

<%= render "form", song: @song, artists: @artists %>